{
 "title": "Meshtastic",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "id",
    "label": "Device ID",
    "query": "from(bucket: \"node_info\")\n  |> range(start: -30d)\n  |> keep(columns: [\"_time\",\"id\"])\n  |> group(columns: [\"id\"])\n  |> max(column: \"_time\")  |> group()   |> sort(columns: [\"_time\"], desc: true)\n  |> keep(columns: [\"id\"])\n  |> distinct(column: \"id\")"
   },
   {
    "name": "fw_version",
    "label": "FW Version",
    "query": "from(bucket: \"node_info\")\n  |> range(start: -30d)\n  |> filter(fn: (r) => r.id == \"${id}\")\n  |> keep(columns: [\"fw_version\"]) \n  |> group()\n  |> distinct(column: \"fw_version\")\n  |> sort(columns: [\"fw_version\"])"
   }
  ]
 },
 "panels": [
  { "title": "${id}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "id" },
  {
   "title": "Hardware",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"node_info\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"hwModel\")\n  |> filter(fn: (r) => r.id == \"${id}\")"
    }
   ]
  },
  {
   "title": "Metrics Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"node_info\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"uptimeSeconds\")\n  |> filter(fn: (r) => r.id == \"${id}\")"
    }
   ]
  },
  {
   "title": "Local Uptime",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"node_info\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"localUptimeSeconds\")\n  |> filter(fn: (r) => r.id == \"${id}\")"
    }
   ]
  },
  {
   "title": "Latitude",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"node_info\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"latitude\")\n  |> filter(fn: (r) => r.id == \"${id}\")"
    }
   ]
  },
  {
   "title": "Longitude",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "string" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"node_info\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"longitude\")\n  |> filter(fn: (r) => r.id == \"${id}\")"
    }
   ]
  },
  {
   "title": "Altitude",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "lengthm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"node_info\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._field == \"altitude\")\n  |> filter(fn: (r) => r.id == \"${id}\")"
    }
   ]
  },
  {
   "title": "Heap Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"node_info\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r.id == \"${id}\")\n  |> filter(fn: (r) =>\n    r._field =~ /^(localHeapTotalBytes|localHeapFreeBytes)$/\n  )\n  |> toFloat()\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> pivot(rowKey:[\"_time\"], columnKey:[\"_field\"], valueColumn:\"_value\")\n  |> map(fn: (r) => ({\n        _time: r._time,\n        _value: float(v: int(v: ((float(v: r.localHeapTotalBytes - r.localHeapFreeBytes) / float(v: r.localHeapTotalBytes)) * 100.0 * 100.0))) / 100.0,\n        _field: \"heapUsagePercent\",\n        _measurement: r._measurement\n  }))\n  |> keep(columns: [\"_time\", \"_value\", \"_field\", \"_measurement\"])"
    }
   ]
  },
  {
   "title": "Channel Utilization",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"node_info\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r.id == \"${id}\")\n  |> filter(fn: (r) =>\n    r._field =~ /^(channelUtilization|localChannelUtilization)$/\n  )\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> toFloat()"
    }
   ]
  },
  {
   "title": "Node Num",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "  from(bucket: \"node_info\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r.id == \"${id}\")\n  |> filter(fn: (r) =>\n    r._field =~ /^(localNumOnlineNodes|localNumTotalNodes)$/\n  )\n  |> toFloat()"
    }
   ]
  },
  {
   "title": "Packets",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "  from(bucket: \"node_info\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r.id == \"${id}\")\n  |> filter(fn: (r) =>\n    r._field =~ /^(localNumPacketsTx|localNumPacketsRx|localNumPacketsRxBad)$/\n  )\n  |> toFloat()"
    }
   ]
  },
  {
   "title": "Air Util Tx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "  from(bucket: \"node_info\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r.id == \"${id}\")\n  |> filter(fn: (r) =>\n    r._field =~ /^(airUtilTx|localAirUtilTx)$/\n  )\n  |> toFloat()"
    }
   ]
  },
  {
   "title": "Relay Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "  from(bucket: \"node_info\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r.id == \"${id}\")\n  |> filter(fn: (r) =>\n    r._field =~ /^(localNumTxRelay|localNumTxRelayCanceled)$/\n  )\n  |> toFloat()"
    }
   ]
  },
  {
   "title": "RX Dupe",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "query": "  from(bucket: \"node_info\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._field == \"localNumRxDupe\"\n  )\n  |> filter(fn: (r) => r.id == \"${id}\")"
    }
   ]
  },
  {
   "title": "Battery Level",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "query": "from(bucket: \"node_info\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._field == \"batteryLevel\"\n  )\n  |> filter(fn: (r) => r.id == \"${id}\")"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "query": "from(bucket: \"node_info\")\n  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)\n  |> filter(fn: (r) =>\n    r._field == \"voltage\"\n  )\n  |> filter(fn: (r) => r.id == \"${id}\")"
    }
   ]
  }
 ]
}